apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door2
  template:
    metadata:
      labels:
        app: door2
    spec:
      containers:
        - name: door2
          args: ["2", "33", "redis-service:6379"]
          image: eu.gcr.io/civic-visitor-253912/door1:v1
